[package]
name = "solidity_testing_perf_cargo"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
slang_solidity = { workspace = true, features = [
  "__experimental_bindings_api",
  "__private_compilation_api",
] }
solidity_testing_perf_utils = { workspace = true }
anyhow = { workspace = true }
infra_utils = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
iai-callgrind = { workspace = true }
paste = { workspace = true }
solang = "0.3.2" # __SLANG_INFRA_SOLANG_VERSION__ (keep in sync)
solang-parser = { version = "=0.3.2" } # __SLANG_INFRA_SOLANG_VERSION__ (keep in sync: it fails to compile otherwise)
solar = { version = "=0.1.3", package = "solar-compiler" }

[[bench]]
name = "iai"
harness = false

[lints]
workspace = true
