[package]
name = "solidity_testing_perf_cargo"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
iai-callgrind = { workspace = true }
infra_utils = { workspace = true }
paste = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slang_solidity = { workspace = true, features = ["__private_backend_api", "__private_testing_utils"] }
slang_solidity_v2_common = { workspace = true }
slang_solidity_v2_parser = { workspace = true }
solar = { workspace = true }
solidity_testing_utils = { workspace = true }
streaming-iterator = { workspace = true }
tree-sitter-solidity = { workspace = true }
tree-sitter = { workspace = true }

[[bench]]
name = "slang"
harness = false

[[bench]]
name = "comparison"
harness = false

[lints]
workspace = true
