[package]
name = "solidity_testing_solc"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
codegen_language_definition = { workspace = true }
indicatif = { workspace = true }
infra_utils = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solidity_language = { workspace = true }
url = { workspace = true }
