[package]
name = "solidity_testing_perf_npm"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde_json = { workspace = true }
infra_utils = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
clap = { workspace = true }
solidity_testing_utils = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[lints]
workspace = true
