[package]
name = "solidity_testing_sourcify"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
infra_utils = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slang_solidity = { workspace = true, features = [
  "__private_ariadne_errors",
  "__private_testing_utils",
] }
solidity_testing_perf_utils = { workspace = true }
tar = { workspace = true }

[lints]
workspace = true
