[package]
name = "solidity_testing_sourcify"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
infra_utils = { workspace = true }
rayon = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slang_solidity = { workspace = true, features = [
  "__private_ariadne_errors",
  "__private_backend_api",
  "__private_testing_utils",
] }
slang_solidity_v2_common = { workspace = true, features = ["__private_testing_utils"] }
slang_solidity_v2_parser = { workspace = true, features = ["__private_testing_utils"] }
solidity_testing_utils = { workspace = true }
tar = { workspace = true }

[lints]
workspace = true
