# More Info: https://www.mkdocs.org/user-guide/configuration/

#
# Configuration:
#

site_name: "Slang"
site_description: >
  A modular set of compiler APIs empowering the next
  generation of Solidity code analysis and developer tooling.
  Written in Rust and distributed in multiple languages.

repo_name: "NomicFoundation/slang"
repo_url: "https://github.com/NomicFoundation/slang/"
site_url: "https://NomicFoundation.github.io/slang/"
edit_uri: "edit/main/documentation/public"

docs_dir: "./public"
site_dir: "./target/site" # _SLANG_MKDOCS_DOCUMENTATION_SITE_DIR_ (keep in sync)
exclude_docs: |
  /user-guide/node_modules
  /user-guide/target

validation:
  nav:
    absolute_links: "warn"
    not_found: "warn"
    omitted_files: "warn"
  links:
    absolute_links: "warn"
    anchors: "warn"
    not_found: "warn"
    unrecognized_links: "warn"

#
# Footer:
#

copyright: >
  Copyright (c) 2022-2024 Nomic Foundation |
  <b><a target="_blank" href="https://github.com/NomicFoundation/slang/blob/main/LICENSE">License</a></b> |
  <b><a target="_blank" href="https://hardhat.org/privacy-policy.html">Privacy Policy</a></b> |
  <b><a href="#__consent">Cookie Settings</a></b>

extra:
  analytics:
    provider: "google"
    property: "G-VKCEJVZ6KG"
  consent:
    title: "Cookie Consent"
    description: >
      We use cookies to recognize your visits and preferences, as well as
      to measure the effectiveness of our documentation, and whether users
      find what they're searching for.
      With your consent, you're helping us to make our documentation better.
    actions:
      - "accept"
      - "reject"
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/NomicFoundation/slang/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/nomicfoundation/"
    - icon: "fontawesome/solid/link"
      link: "https://nomic.foundation/"
  version:
    provider: "mike"
    alias: true
    default: "latest"

#
# Extensions:
#

markdown_extensions:
  - "admonition"
  - "attr_list"
  - "def_list"
  - "pymdownx.caret"
  - "pymdownx.details"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.mark"
  - "pymdownx.snippets":
      base_path: !ENV "REPO_ROOT"
      check_paths: true
      dedent_subsections: true
  - "pymdownx.superfences"
  - "pymdownx.tabbed":
      alternate_style: true
  - "pymdownx.tasklist":
      custom_checkbox: true
  - "pymdownx.tilde"
  - "tables"
  - "toc":
      permalink: "#"

plugins:
  - "search"
  - "literate-nav":
      nav_file: ".navigation.md" # use a dot file name, to be excluded from public pages
      markdown_extensions: []
  - "mike":
      canonical_version: "latest"
  - "minify":
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
      css_files:
        - "./assets/stylesheets/colors.css"
      js_files:
        - "./assets/javascripts/grammar-navigation.js"

extra_css:
  - "./assets/stylesheets/colors.css"
extra_javascript:
  - "./assets/javascripts/grammar-navigation.js"

#
# Theme:
#

theme:
  name: "material"
  custom_dir: "./overrides/"
  features:
    - "content.action.edit"
    - "content.action.view"
    - "content.code.copy"
    - "content.tabs.link"
    - "navigation.expand"
    - "navigation.footer"
    - "navigation.indexes"
    - "navigation.sections"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.top"
    - "search.highlight"
    - "search.suggest"
    - "toc.follow"
  font:
    text: "Nunito"
    code: "Roboto Mono"
  icon:
    edit: "material/file-document-edit-outline"
    view: "material/file-eye-outline"
  palette:
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: "material/brightness-7"
        name: "Switch to light mode"
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/brightness-4"
        name: "Switch to dark mode"
