name: "jobs/ci"

on:
  # Run when invoked from other workflows:
  workflow_call: {}

jobs:
  run:
    runs-on: "ubuntu-22.04" # _SLANG_DEV_CONTAINER_BASE_IMAGE_ (keep in sync)

    steps:
      #
      # _DEVCONTAINER_PREPARATION_STEPS_ (keep in sync)
      # Cache is updated in this workflow, and reused in subsequent workflows.
      # Note: always start with a fresh cache when running on the main branch.
      #

      - name: "Clone repository"
        uses: "actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b"

      - name: "Restore CI cache"
        if: "${{ github.ref_name != 'main' }}"
        uses: "actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9"
        with:
          key: "cache-${{ github.ref_name }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('package-lock.json') }}"
          restore-keys: |
            cache-${{ github.ref_name }}-
            cache-main-
            cache-
          path: |
            ~/.cache/hermit/
            ~/.local/share/virtualenvs/
            .hermit/

      #
      # Run all CI steps in order: _SLANG_INFRA_CI_STEPS_ORDERED_ (keep in sync)
      #

      - run: "scripts/bin/infra setup"
      - run: "scripts/bin/infra check"
      - run: "scripts/bin/infra test"
      - run: "scripts/bin/infra lint"

      #
      # Update cache files:
      # _DEVCONTAINER_PREPARATION_STEPS_ (keep in sync)
      #

      - name: "Save cache"
        uses: "actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9"
        with:
          key: "cache-${{ github.ref_name }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('package-lock.json') }}"
          path: |
            ~/.cache/hermit/
            ~/.local/share/virtualenvs/
            .hermit/
